// fragment: spawn_protection (perception)
// purpose: the ONE answer to "may this cell be CHANGED" — the world's spawn-protected square, sensed
//          from the server rather than assumed, asked before any decision that would break or place a
//          block there.
//
// ── WHAT THE RULE ACTUALLY IS (the game's own shape, not an approximation) ────────────────────────
// A vanilla server refuses block BREAKS and block PLACEMENTS by non-op players inside a square centred
// on the WORLD SPAWN. Four properties, each of which decides something in this file:
//   · CHEBYSHEV ON X/Z: `max(|x-sx|, |z-sz|) <= radius` — a square, not a circle. A radius of 16 is a
//     33x33 footprint, not a 16-block disc, so a circular test under-protects the corners by 6 blocks.
//   · INFINITE IN Y. There is no vertical term at all: the square is a column from bedrock to sky. A
//     mine shaft sunk 60 blocks under spawn is inside it exactly as much as the grass on top.
//   · BREAK **AND** PLACE. Reading this as a mining rule leaves every build path unguarded.
//   · OVERWORLD ONLY. The other dimensions have no protected spawn.
//
// ── WHY THE FLEET NEEDS ITS OWN GATE AND CANNOT LEAN ON THE SERVER'S REFUSAL ──────────────────────
// The server refuses SILENTLY. It sends nothing the client can see — no revert, no error — and
// mineflayer's dig resolves optimistically off an AIR event it manufactures in its own world model
// (`finishDigging` -> local `_updateBlockState`; the server is never in the loop). So a refused break
// reads as a successful one at every layer above it: the bot believes it opened a hole, walks into a
// block that never left, collects nothing, and strands itself with no error anywhere in the trace.
// dig_authority's re-sense cannot catch this class either — it re-reads the same client model that
// lied, and there is no revert to land. A refusal the world will not report has to be predicted, which
// means the fleet has to hold the rule itself.
//
// ── THE GATE BINDS EVERY BOT, INCLUDING ONE THE SERVER WOULD EXEMPT (Invariant E, Law 19) ─────────
// Vanilla exempts operators, and disables the rule outright when the ops list is empty. This module
// reads NEITHER condition, deliberately: an op'd bot is gated exactly like a non-op one. Two reasons,
// and both are structural rather than a preference.
//   1. A constraint honoured only where it cannot be defeated is not a constraint (Invariant E). An
//      exemption granted by an accident of which names happen to sit in a config file is the Rogue
//      Machine error Law 19 names — the machine claiming operational rights no other agent in the
//      shared world holds.
//   2. Keying on op status would make two bots in one fleet obey different world rules, so the same
//      job would succeed or strand depending only on which bot claimed it. A fleet whose members
//      disagree about what the world permits cannot be reasoned about from its trace.
// The cost is real and accepted: an op'd bot refuses work the server would have let it do. That is the
// point — the refusal is what makes honouring the rule mean anything.
//
// ── THE CENTRE IS SENSED, THE RADIUS IS DECLARED, AND NEITHER IS GUESSED ──────────────────────────
// CENTRE: the server states the world spawn in its `spawn_position` packet, so it is read off the wire
// rather than remembered (Invariant B). It is re-read every time the packet arrives, which is also how
// a `/setworldspawn` mid-run moves the square instead of leaving a stale one behind.
//
// NOT `bot.spawnPoint`. mineflayer initialises that field to (0,0,0) and overwrites it when the packet
// lands, so a read before the packet returns a well-formed falsehood indistinguishable from a real
// spawn at the origin — and worlds generated by this fleet spawn at x=0,z=0, which is precisely the
// value that would make the bug invisible (Law 13: never default a missing field; Law 26: a form check
// cannot see a falsehood). This module latches the packet itself and remembers WHETHER it arrived, so
// "not known yet" is a state a caller can be told about rather than a coordinate it silently trusts.
//
// RADIUS: no packet carries it — it is a server property the client is never told. It therefore lives
// in architect_config as a declared belief about the world, and `fleet_control` ASSERTS that same
// constant into `server.properties` at every launch. One number, one author: the launcher cannot set a
// square the bots do not know about, and the bots cannot believe in a square the launcher did not set.
//
// ── TWO QUESTIONS, AND CALLERS MUST NOT SUBSTITUTE ONE FOR THE OTHER ──────────────────────────────
// `isSpawnProtected` answers "is this cell inside the square", and answers FALSE when the centre is not
// known yet. It is for SELECTION — dropping candidates from a scan. A selector that treated "unknown"
// as protected would discard the whole world and report an empty forest.
//
// `spawnProtectionVerdict` answers "may this verb run here", and REFUSES when the centre is not known
// (Law 13, default-stopped: prove safe to continue). It is for the world-altering VERBS — the dig
// authority and every placement. That is the right place for the strict half, because the verb is
// where the irreversible act happens and a refused dig is recoverable by a replan while a phantom one
// strands the bot.
//
// In practice the strict half never fires: vanilla sends `spawn_position` during login, before the
// body is spawned, so the latch is set before any fragment runs. A login that did not produce it is a
// broken session in which no work is possible anyway — and it now says so instead of mining phantoms.

'use strict';

const watcher = require('@kernel/watcher');
const { SPAWN_PROTECTION_RADIUS } = require('@thinking/architect_config');

// Per-bot, not module-global: the headless bench builds several bodies in one process, and a shared
// latch would let one bot's world spawn answer another's question. WeakMap so the entry dies with the
// bot rather than outliving it (Law 8 — nothing outlives its owner).
const _zones = new WeakMap();

// zoneFor — the latch for this body, found through the PROTOTYPE CHAIN and not by identity alone.
//
// THE WRONG TURN THIS FIXES, because it is invisible and it shipped: a WeakMap keys on object identity,
// and this fleet legitimately hands wrapped bots to its hottest consumer. `pathfinding_utils` swaps the
// search onto a fast voxel view built with `Object.create(bot)` — a NEW object whose prototype is the
// real body, so `world`, `entity` and `inventory` still resolve while block reads go through a faster
// table. `_zones.get(view)` misses. The result is the worst shape a gate can have: the module answers
// "no protected square here" with total confidence, the route search generates dig edges straight
// through the keep-out, and the refusal lands at the swing instead — so the bot plans a route it cannot
// walk, is refused, replans the same route, and gives up. Measured on the first live drill: 240 dig
// refusals, five A* searches cut off at 5000 ms each, and a body that never left the square.
//
// Walking the chain fixes it for every wrapper, present and future, rather than for the one that was
// found — a caller cannot be required to remember to unwrap before asking, because the cost of
// forgetting is a silently disarmed gate rather than an error. Chains here are one or two links, so
// this is a couple of misses before the hit.
function zoneFor(bot) {
  for (let o = bot; o; o = Object.getPrototypeOf(o)) {
    const z = _zones.get(o);
    if (z) return z;
  }
  return null;
}

// arm(bot) — latch the world spawn off the server's own packet.
//
// MUST BE CALLED IMMEDIATELY AFTER createBot, before login completes. `spawn_position` arrives during
// the login sequence, so a listener registered from the `spawn` handler is registered after the only
// packet it exists to catch and would never fire — the latch would read "unknown" for the whole run
// and every dig would be refused. Registering on the raw client stream is the same surface mineflayer's
// own spawn_point plugin uses; this is a peer listener on a public event, not a reach into its state.
function armSpawnProtection(bot) {
  if (!bot || !bot._client) {
    throw new Error('[spawn_protection] CODING VIOLATION: armSpawnProtection called with no client to listen on.');
  }
  if (_zones.has(bot)) return;                    // idempotent — a second arm would double-count nothing but is noise
  _zones.set(bot, { known: false, sx: 0, sz: 0 });
  bot._client.on('spawn_position', (packet) => {
    const loc = packet && packet.location;
    if (!loc || typeof loc.x !== 'number' || typeof loc.z !== 'number') {
      // The packet is the ONLY source for the centre, so a malformed one cannot be repaired or
      // defaulted — say what arrived and leave the latch as it was (Law 13).
      watcher.warn('spawn_protection', `spawn_position carried no usable location (${JSON.stringify(loc)}) — world spawn still ${_zones.get(bot).known ? 'the previously received value' : 'UNKNOWN'}.`);
      return;
    }
    const sx = Math.floor(loc.x);
    const sz = Math.floor(loc.z);
    const prev = _zones.get(bot);
    _zones.set(bot, { known: true, sx, sz });
    if (!prev.known) {
      watcher.summary('spawn_protection', `World spawn received: (${sx},${sz}). ${describeSpawnProtection(bot)}`);
    } else if (prev.sx !== sx || prev.sz !== sz) {
      // A moved world spawn moves the square under work already planned against the old one. Loud,
      // because a job that was legal when it was posted may not be legal when it runs.
      watcher.warn('spawn_protection', `World spawn MOVED (${prev.sx},${prev.sz}) -> (${sx},${sz}) — the protected square moved with it. ${describeSpawnProtection(bot)}`);
    }
  });
}

// spawnProtectionBox(bot) — the square as plain numbers, or null when there is nothing to avoid
// (rule switched off, or centre not yet known).
//
// HOISTED BY THE HOT CALLER, NOT ASKED PER CELL. The route search evaluates hundreds of thousands of
// cells in one pass, and a WeakMap lookup plus a config read per cell is pure waste against two
// subtractions. A* takes this box once per search and compares against it inline; everything cooler
// asks isSpawnProtected directly.
function spawnProtectionBox(bot) {
  if (!(SPAWN_PROTECTION_RADIUS > 0)) return null;         // radius 0 (or absent) = the world has no such rule
  const z = zoneFor(bot);
  if (!z || !z.known) return null;
  return {
    centerX: z.sx,
    centerZ: z.sz,
    radius: SPAWN_PROTECTION_RADIUS,
    minX: z.sx - SPAWN_PROTECTION_RADIUS, maxX: z.sx + SPAWN_PROTECTION_RADIUS,
    minZ: z.sz - SPAWN_PROTECTION_RADIUS, maxZ: z.sz + SPAWN_PROTECTION_RADIUS,
  };
}

// isSpawnProtected(bot, x, z) — is this column inside the square?
//
// Takes bare X and Z rather than a block or a position: every caller that matters asks about a cell it
// has not fetched a block for (the search asks per node; a footprint scan asks per column), and there
// is no Y term to want. Floors both, because an entity position is a float and the square is drawn on
// cell lines.
//
// FALSE WHEN THE CENTRE IS UNKNOWN — see the two-questions note in the header. Selection callers want
// that; verb callers must use spawnProtectionVerdict instead.
function isSpawnProtected(bot, x, z) {
  const box = spawnProtectionBox(bot);
  if (!box) return false;
  return Math.max(Math.abs(Math.floor(x) - box.centerX), Math.abs(Math.floor(z) - box.centerZ)) <= box.radius;
}

// isSpawnProtectedAt(bot, pos) — the same question for callers already holding a position/Vec3.
function isSpawnProtectedAt(bot, pos) {
  if (!pos || typeof pos.x !== 'number' || typeof pos.z !== 'number') return false;
  return isSpawnProtected(bot, pos.x, pos.z);
}

// firstSpawnProtectedCell(bot, cells) — the first cell of a group that lies inside the square, or null.
//
// Group-shaped because most DECISIONS are about a region rather than a block: a building footprint, a
// mine cell's 5x5x5 body, a stone column's shaft. Returning the offending cell rather than a boolean is
// what lets the caller name WHICH part of its candidate was refused (Law 13 — state the cause).
function firstSpawnProtectedCell(bot, cells) {
  const box = spawnProtectionBox(bot);
  if (!box || !cells) return null;
  for (const c of cells) {
    if (!c || typeof c.x !== 'number' || typeof c.z !== 'number') continue;
    if (Math.max(Math.abs(Math.floor(c.x) - box.centerX), Math.abs(Math.floor(c.z) - box.centerZ)) <= box.radius) return c;
  }
  return null;
}

// spawnProtectionVerdict(bot, pos, verb) — MAY THIS WORLD-ALTERING VERB RUN HERE?
//
// The strict half (Law 13, default-stopped). Three outcomes and each names its own cause, because a
// refusal that does not say why is the same silence this module exists to remove:
//   · rule off        -> allowed
//   · centre unknown  -> REFUSED; the fleet cannot tell protected ground from open ground, so it does
//                        not swing. Prove safe to continue, never prove unsafe to stop.
//   · inside the box  -> REFUSED; the server would refuse it too, without saying so.
// `verb` is the caller's own word for what it wanted to do ('dig', 'place'), quoted straight back into
// the reason so the trace reads as the act that was stopped rather than as a generic gate firing.
function spawnProtectionVerdict(bot, pos, verb) {
  if (!(SPAWN_PROTECTION_RADIUS > 0)) return { allowed: true, why: null };
  const z = zoneFor(bot);
  if (!z || !z.known) {
    return {
      allowed: false,
      why: `${verb} refused — the world spawn is not known yet (no spawn_position packet received), so this fleet cannot tell spawn-protected ground from open ground. A protected ${verb} is refused by the server SILENTLY, so proceeding would mine phantoms; default-stopped until the world says where spawn is.`,
    };
  }
  if (!pos || typeof pos.x !== 'number' || typeof pos.z !== 'number') {
    throw new Error(`[spawn_protection] CODING VIOLATION: spawnProtectionVerdict called with no position (verb='${verb}').`);
  }
  const dx = Math.abs(Math.floor(pos.x) - z.sx);
  const dz = Math.abs(Math.floor(pos.z) - z.sz);
  const d = Math.max(dx, dz);
  if (d <= SPAWN_PROTECTION_RADIUS) {
    return {
      allowed: false,
      why: `${verb} refused at (${Math.floor(pos.x)},${pos.y != null ? Math.floor(pos.y) : '?'},${Math.floor(pos.z)}) — inside the spawn-protected square (centre ${z.sx},${z.sz}, radius ${SPAWN_PROTECTION_RADIUS}; this cell is ${d} out). The server refuses breaks and placements here and reports nothing, so the fleet treats the whole column as unbreakable and unbuildable. Route around it or pick a target outside the square.`,
    };
  }
  return { allowed: true, why: null };
}

// describeSpawnProtection(bot) — one line for a log or a report. Kept here so every place that prints
// the square prints the same sentence from the same numbers (Law 16), rather than each caller
// re-deriving bounds and drifting on the corner arithmetic.
function describeSpawnProtection(bot) {
  if (!(SPAWN_PROTECTION_RADIUS > 0)) return 'Spawn protection is OFF (radius 0) — no cell is off-limits.';
  const box = spawnProtectionBox(bot);
  if (!box) return `Spawn protection radius ${SPAWN_PROTECTION_RADIUS} is declared but the world spawn is NOT KNOWN yet — every dig and placement is refused until it arrives.`;
  const side = box.radius * 2 + 1;
  return `Spawn-protected square: centre (${box.centerX},${box.centerZ}), radius ${box.radius} -> x ${box.minX}..${box.maxX}, z ${box.minZ}..${box.maxZ} (${side}x${side}, full height). No breaking, no placing, any bot, op or not.`;
}

module.exports = {
  armSpawnProtection,
  spawnProtectionBox,
  isSpawnProtected,
  isSpawnProtectedAt,
  firstSpawnProtectedCell,
  spawnProtectionVerdict,
  describeSpawnProtection,
};
